### ISSUE TITLE
Not working!

### ISSUE THREAD

**Issue by anoying-kid** [E4crypt3d/WhatsAppCrashingToolv1.2#1]
Tried not, give me brief description how it works??

**Comment by E4crypt3d** [comment]
works perfect with termux
whats the error?

**Comment by anoying-kid** [comment]
> works perfect with termux whats the error?

Don't really understand the procedure, do i've to copy the text? If yes it really hard to copy it and also getting 
`/data/data/com.termux/files/usr/bin/which: this version of `which' is deprecated; use `command -v' in scripts instead.`

**Comment by E4crypt3d** [comment]
check it again sir its working now

**Comment by anoying-kid** [comment]
> check it again sir its working now

Yes it works but the whatsapp still didn't crash yet, i can easily read message from another device.

**Comment by E4crypt3d** [comment]
Its doesn't work with IOS device

**Comment by anoying-kid** [comment]
share the screenshot or video how it working still not working just lagging.
